spring.application.name=DataGenerator
server.port=${GENERATOR_PORT}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
kafka.mes.topic =${KAFKA_MES_TOPIC}
kafka.mes.group=${KAFKA_MES_GROUP}
kafka.scada.topic =${KAFKA_SCADA_TOPIC}
kafka.scada.group=${KAFKA_SCADA_GROUP}
kafka.lims.topic =${KAFKA_LIMS_TOPIC}
kafka.lims.group=${KAFKA_LIMS_GROUP}
spring.kafka.consumer.auto-offset-reset=earliest

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true