spring.application.name=DataMartBackend
server.port=${BACKEND_PORT}

spring.resources.static-locations: classpath:/static/,classpath:/fonts/

spring.datasource.url=${DB_URL}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
kafka.mes.topic =${KAFKA_MES_TOPIC}
kafka.mes.group=${KAFKA_MES_GROUP}
kafka.scada.topic =${KAFKA_SCADA_TOPIC}
kafka.scada.group=${KAFKA_SCADA_GROUP}
kafka.lims.topic =${KAFKA_LIMS_TOPIC}
kafka.lims.group=${KAFKA_LIMS_GROUP}
spring.kafka.consumer.auto-offset-reset=earliest

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

jwt.secret=${JWT_SECRET}